---
name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
  test:
    uses: ./.github/workflows/python.yml
    needs: [pre-commit]
  release:
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit # pass all secrets
    needs: [test]
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
